# Generated by Django 4.0.1 on 2022-04-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Date',
        ),
    ]
